// ============================================================================
// Guide data — Varashta Minion (Disciple of Rasha) Sorceress campaign guide
//
// This is a plain data file consumed by guide.html (the presentation engine).
// To author a NEW guide, copy this file, change the contents, and open:
//     guide.html?build=your-new-file-name
// (drop the ".js" — the engine loads guide-builds/<build>.js)
//
// SCHEMA
//   window.GUIDE = {
//     title, subtitle,                         // top-of-screen labels
//     reminders: [string, ...],                // always-on footer notes
//     reference: { sections: [ ... ] },        // "?" overlay content
//     steps: [ { act, title, body, meta?, level?, danger?, loadout? }, ... ]
//   }
//
//   reference.sections entries:
//     { heading, type: "text",  body }                       // body: newlines ok
//     { heading, type: "table", columns: [...], rows: [[...], ...] }
//
//   steps entries:
//     act     — group label (e.g. "Act 1"); shown as a badge, divider on change
//     title   — the big "do this now" line
//     body    — smaller detail under the title
//     level   — optional expected player level (e.g. "6", "14 (catch-up)")
//     danger  — optional area danger (e.g. "Sprint", "Cautious", "Dangerous", "Death Wish")
//     meta    — optional free-form note (e.g. "Every boss")
//     loadout — optional list of currently-equipped skills/supports:
//               [ { skill, supports? }, ... ]  e.g. { skill: "Spark", supports: ["Unleash"] }
// ============================================================================
window.GUIDE = {
  title: "Varashta Minion",
  subtitle: "Disciple of Rasha — Sorceress campaign leveling",

  reminders: [
    "BOSS — Pounce → Thunderstorm → Kari's Brutality ×2 → Kari's Deception ×3 → Kari's Brutality ×2 → Kari's Deception ×2 → repeat",
    "GEM SWAP — clear = Magnified Area · boss = Concentrated Area (on Kari's Command)",
    "SAVE every support gem you find — you need a pile of them for the swap",
  ],

  reference: {
    sections: [
      {
        heading: "Boss rotation",
        type: "text",
        body: "Pounce → Thunderstorm → Kari's Brutality ×2 → Kari's Deception ×3 → Kari's Brutality ×2 → Kari's Deception ×2 → repeat\n\nNon-boss / AoE: Magnified Area on Kari's Command\nBoss / single-target: Concentrated Area on Kari's Command",
      },
      {
        heading: "Item priority (Varashta)",
        type: "table",
        columns: ["Slot", "Most", "→", "→", "Least"],
        rows: [
          ["Sceptre", "Ranks to Minion Skills", "% Spirit", "Allies gain damage", "Allies crit chance"],
          ["Helm", "Ranks to Minion Skills", "Life", "Life + ES", "Crit chance"],
          ["Boots", "Movement Speed", "Resistance", "Life", "Energy Shield"],
          ["Amulet", "Ranks to All Spells", "Cast Speed", "Mana", "Energy Shield"],
          ["Armor", "Resistance", "Life", "Energy Shield", "Mana"],
        ],
      },
      {
        heading: "Items to hunt by level",
        type: "table",
        columns: ["Gear", "Affix", "Level"],
        rows: [
          ["Sceptre", "+1 to all Minion Skills", "2"],
          ["Sceptre", "+2 to all Minion Skills", "25"],
          ["Sceptre", "+3 to all Minion Skills", "55"],
          ["Helm", "+1 to all Minion Skills", "5"],
          ["Helm", "+2 to all Minion Skills", "41"],
        ],
      },
      {
        heading: "Varashta gem priority",
        type: "table",
        columns: ["#", "Skill gem", "Support 1", "Support 2", "Support 3"],
        rows: [
          ["1", "Kari's Command", "Bidding I/II", "Conc. Area", "Magnified Area I/II"],
          ["2", "Pounce", "Mark for Death", "Prolonged Duration I/II", ""],
          ["3", "Thunderstorm", "Living Lightning", "Prolonged Duration I/II", "Magnified Area I/II"],
          ["4", "Skeletal Sniper", "Last Gasp", "", ""],
          ["5", "Skeletal Arsonist", "Last Gasp", "", ""],
          ["6", "Skeletal Frost Mage", "Last Gasp", "", ""],
          ["7", "Bind Spectre", "Last Gasp", "", ""],
          ["8", "Skeletal Reaver", "Last Gasp", "", ""],
          ["9", "Skeletal Storm Mage", "Last Gasp", "", ""],
          ["10", "Skeletal Brute", "Last Gasp", "", ""],
        ],
      },
      {
        heading: "Gems needed for the level-20 swap",
        type: "text",
        body: "2× Level 5 Skill Gems\n3× Level 1 Support Gems\n3× Level 2 Support Gems",
      },
      {
        heading: "Area levels & danger",
        type: "table",
        columns: ["Act", "Area", "Level", "Danger"],
        rows: [
          ["Act 1", "Clearfell", "1", "Sprint"],
          ["Act 1", "Grelwood", "1", "Sprint"],
          ["Act 1", "Red Vale", "2", "Cautious"],
          ["Act 1", "Grim Tangle", "3", "Cautious"],
          ["Act 1", "Cemetery", "4", "Sprint"],
          ["Act 1", "Tomb of Consort", "6 (catch-up)", "Death Wish"],
          ["Act 1", "Mausoleum", "6", "Cautious"],
          ["Act 1", "Hunting Grounds", "7 (catch-up)", "Cautious"],
          ["Act 1", "Freythorn", "8", "Cautious"],
          ["Act 1", "Farmlands", "9", "Sprint"],
          ["Act 1", "Ogham Village", "10", "Sprint"],
          ["Act 1", "Manor Ramparts", "11", "Dangerous"],
          ["Act 1", "Ogham Manor", "12 (catch-up)", "Dangerous"],
          ["Act 2", "Vastiri Outskirts", "13", "Sprint"],
          ["Act 2", "Mawdun Quarry", "14 (catch-up)", "Sprint"],
          ["Act 2", "Mawdun Mine", "15", "Cautious"],
          ["Act 2", "Traitors Passage", "16", "Sprint"],
          ["Act 2", "Halani Gates", "16", "Cautious"],
          ["Act 2", "Trial of Sekhemas", "18", "Sprint"],
          ["Act 2", "Keth", "21", "Sprint"],
          ["Act 2", "Lost City", "22", "Cautious"],
          ["Act 2", "Buried Shrines", "23", "Cautious"],
          ["Act 2", "Mastodon Badlands", "22 (catch-up)", "Sprint"],
          ["Act 2", "Bone Pits", "23", "Sprint"],
          ["Act 2", "Valley of the Titans", "22", "Sprint"],
          ["Act 2", "Titan Grotto", "23", "Cautious"],
          ["Act 2", "Deshar", "24", "Dangerous"],
          ["Act 2", "Path of Mourning", "25", "Sprint"],
          ["Act 2", "Spires of Deshar", "26", "Cautious"],
          ["Act 2", "Dreadnaught", "27 (catch-up)", "Dangerous"],
          ["Act 2", "Dreadnaught Vanguard", "28 (catch-up)", "Dangerous"],
          ["Act 3", "Sandswept Marsh", "29", "Sprint"],
          ["Act 3", "Jungle Ruins", "30", "Sprint"],
          ["Act 3", "Infested Barrens", "31", "Sprint"],
          ["Act 3", "Azok Bog", "32", "Cautious"],
          ["Act 3", "Chimeral Wetlands", "32", "Sprint"],
          ["Act 3", "Jiquani's Machinarium", "32", "Cautious"],
          ["Act 3", "Jiquani's Sanctum", "33", "Cautious"],
          ["Act 3", "Trial of Chaos", "33", "Cautious"],
          ["Act 3", "Matlan Waterways", "34 (catch-up)", "Cautious"],
          ["Act 3", "Drowned City", "35 (catch-up)", "Cautious"],
          ["Act 3", "Apex of Filth", "36", "Cautious"],
          ["Act 3", "Temple of Kopec", "37", "Cautious"],
          ["Act 3", "Utzaal", "38 (catch-up)", "Death Wish"],
          ["Act 3", "Aggorat", "39", "Dangerous"],
          ["Act 3", "Black Chambers", "40", "Dangerous"],
          ["Act 4", "Isle of Kin", "41", "Cautious"],
          ["Act 4", "Volcanic Warrens", "41", "Sprint"],
          ["Act 4", "Eye of Hinekora", "42", "Sprint"],
          ["Act 4", "Halls of the Dead", "43", "Cautious"],
          ["Act 4", "Shrike Island", "44 (catch-up)", "Death Wish"],
          ["Act 4", "Whakapanu Island", "44 (catch-up)", "Death Wish"],
          ["Act 4", "Singing Caverns", "45", "Cautious"],
          ["Act 4", "Abandoned Prison", "46", "Cautious"],
          ["Act 4", "Solitary Confinement", "47", "Cautious"],
          ["Act 4", "Kedge Bay", "47", "Sprint"],
          ["Act 4", "Journey's End", "48", "Cautious"],
          ["Act 4", "Arastas", "48", "Dangerous"],
          ["Act 4", "Excavation", "49 (catch-up)", "Cautious"],
          ["Act 4", "Ngakanu", "50", "Dangerous"],
          ["Act 4", "Heart of the Tribe", "51", "Death Wish"],
        ],
      },
    ],
  },

  steps: [
    { act: "Act 1", title: "Kill Bloated Miller", body: "Wake on the beach. Run straight to Bloated Miller — don't kill anything else. Kill him, then go to Clearfell Encampment.", level: "1", danger: "Sprint" },
    { act: "Act 1", title: "Frost Bomb + Contagion", body: "Grab Frost Bomb from Renly at Clearfell. Grab the level-1 gem in the encampment and equip Contagion." },
    { act: "Act 1", title: "Kill the Cold Witch", body: "Kill the Cold Witch, then head to Grelwood.", level: "1", danger: "Sprint" },
    { act: "Act 1", title: "Craft spell damage on staff", body: "Watch for Orbs of Transmutation/Augmentation and staffs. Slam them into your staff trying to hit a Spell Damage mod — it makes Act 1→2 a breeze.", level: "1", danger: "Sprint" },
    { act: "Act 1", title: "Areagne (Grelwood hut)", body: "At the hut: cast Frost Bomb OUTSIDE before spawning her (applies exposure + cold infusion). Go inside, drop another Frost Bomb, then unleash cold-infused Spark + normal Spark.", level: "1", danger: "Sprint" },
    { act: "Act 1", title: "Unleash → Spark", body: "Use the support gem to put Unleash on Spark.", level: "1", danger: "Sprint", loadout: [{skill: "Spark", supports: ["Unleash"]}, {skill: "Contagion"}, {skill: "Frostbomb"}] },
    { act: "Act 1", title: "Waypoints + Red Vale", body: "Grab the Grelwood waypoint and the Grim Tangle checkpoint, then clear Red Vale.", level: "2", danger: "Cautious" },
    { act: "Act 1", title: "First shop", body: "Back to town: buy scrolls, identify items, sell junk." },
    { act: "Act 1", title: "Shop: staff + scepter (Una)", body: "From Una look for (1) a staff requiring level 3+ (pref. 6 → level-3 intrinsic skill) with Spell Damage and/or +2 to all skills, and (2) a scepter with +1 to minion/dominion skills." },
    { act: "Act 1", title: "Shop: boots + helm (Renly)", body: "From Renly look for boots with Movement Speed and a helm with +1 to minion/dominion skills. Shop refreshes one item each level." },
    { act: "Act 1", title: "Free the Hooded One → Grim Tangle", body: "Free the Hooded One, then head to Grim Tangle.", level: "3", danger: "Cautious" },
    { act: "Act 1", title: "Level 6: Essence Drain", body: "At level 6, use your level-3 gem on Essence Drain. Swap Unleash from Spark to Contagion (3 targets).", level: "3", danger: "Cautious" },
    { act: "Act 1", title: "Rotten Druid", body: "For this boss, swap Unleash to the staff's intrinsic skill (Ice Shards / Lightning Bolt / Firebolt / Chaos Bolt). Rotate Essence Drain + intrinsic. Non-boss = keep Unleash on Contagion.", level: "3", danger: "Cautious" },
    { act: "Act 1", title: "Zenith → Essence Drain", body: "After the Rotten Druid, use the support gem to put Zenith into Essence Drain.", level: "3", danger: "Cautious", loadout: [{skill: "Essence Drain", supports: ["Zenith"]}, {skill: "Contagion", supports: ["Unleash"]}, {skill: "Spark"}] },
    { act: "Act 1", title: "Cemetery → Consort", body: "In the Cemetery, find the Consort and Mausoleum checkpoints. Go into the Consort first and find the rare chest for a support gem.", level: "4", danger: "Sprint" },
    { act: "Act 1", title: "Controlled Destruction → Essence Drain", body: "Put Controlled Destruction into Essence Drain. Then kill the Consort boss.", level: "6 (catch-up)", danger: "Death Wish" },
    { act: "Act 1", title: "Mausoleum → Lachlann", body: "Mausoleum: kill the predator. Then kill Lachlann.", level: "6", danger: "Cautious" },
    { act: "Act 1", title: "Hunting Grounds", body: "Head to the Hunting Grounds, waypoint back to Clearfell, free the Hooded One, check Renly for boots/helm.", level: "7 (catch-up)", danger: "Cautious" },
    { act: "Act 1", title: "Talisman + Strength node", body: "If you still have no Talisman, buy one and equip it on weapon set 2. Talk to the Hooded One to identify. In the passive tree, go LEFT and grab one Strength node (needed for Pounce)." },
    { act: "Act 1", title: "Flasks", body: "Check Una, sell items, check staff + scepter. Buy upgraded Mana and Life flasks." },
    { act: "Act 1", title: "Pounce", body: "In the Hunting Grounds, use the level-3 skill gem from Lachlann to equip Pounce (Primal tab).", level: "7 (catch-up)", danger: "Cautious" },
    { act: "Act 1", title: "Weapon-set binding", body: "Menu: set Essence Drain and Contagion to weapon set 1, so you don't cast them while only the Talisman (set 2) is equipped." },
    { act: "Act 1", title: "Hunting Grounds corners", body: "Check all 4 corners for the Crowbell checkpoint, the Ogham Farmlands checkpoint, and a cove with a rare (support gem).", level: "7 (catch-up)", danger: "Cautious" },
    { act: "Act 1", title: "Magnified Effect → Contagion", body: "Kill Crowbell + the rare for a support gem. Put Magnified Effect on Contagion.", level: "7 (catch-up)", danger: "Cautious", loadout: [{skill: "Essence Drain", supports: ["Zenith", "Controlled Destruction"]}, {skill: "Contagion", supports: ["Unleash", "Magnified Effect"]}, {skill: "Orb of Storms"}, {skill: "Frostbomb"}] },
    { act: "Act 1", title: "Freythorn", body: "Clear Freythorn, then back to town for another shop (staff, scepter, boots, helm).", level: "8", danger: "Cautious" },
    { act: "Act 1", title: "Ogham Farmlands → barricade", body: "From the Hunting Grounds checkpoint, enter Ogham Farmlands. Follow the road to a barricade — Pounce over it to the loot hut.", level: "9", danger: "Sprint" },
    { act: "Act 1", title: "Crop circle", body: "Follow the path to the crop circle. ONE attempt — be cautious. Killing the pack drops a level-4 skill gem → upgrade Essence Drain to 4.", level: "9", danger: "Sprint" },
    { act: "Act 1", title: "Ogham Village", body: "Find Renly's tools, kill the Executioner, free Latli, portal to town.", level: "10", danger: "Sprint" },
    { act: "Act 1", title: "Level 5 gem + last shop", body: "Grab the level-5 skill gem from Latli. Last shop from Una + Renly. Watch for a +1 minion helm/scepter." },
    { act: "Act 1", title: "Save gems + Orb of Storms", body: "Do NOT use extra support gems (save them). If you have an extra skill gem, put it in Orb of Storms and equip." },
    { act: "Act 1", title: "Mana Ramparts", body: "Clear everything with the Essence Drain + Contagion combo (~2–3 levels). Find the Gallows for a support gem.", level: "11", danger: "Dangerous" },
    { act: "Act 1", title: "Ogham Manor", body: "Find and kill the Kennel Mouse for extra HP. Push through to Geonor.", level: "12 (catch-up)", danger: "Dangerous" },
    { act: "Act 1", title: "Geonor", body: "Be level 14. When he says 'no news', cast Orb of Storms + hold Ember Fusillade (lightning infusion). When targetable, Frost Bomb → melt. Repeat until dead.", level: "14", danger: "Dangerous", loadout: [{skill: "Ember Fusillade", supports: ["Zenith", "Controlled Destruction"]}, {skill: "Orb of Storms"}, {skill: "Frostbomb"}, {skill: "Essence Drain", supports: ["Zenith"]}] },
    { act: "Act 1", title: "→ Act 2", body: "Last shop check, then move to Act 2." },

    { act: "Act 2", title: "Vastiri Outskirts", body: "Find the encampment chest for a level-2 support gem (very important). Save ALL support gems.", level: "13", danger: "Sprint" },
    { act: "Act 2", title: "Hyena Lord", body: "Kill the Hyena Lord with the same Geonor rotation.", level: "13", danger: "Sprint" },
    { act: "Act 2", title: "Mawdun Quarry", body: "Follow the quest. Essence Drain + Contagion shine here — kill everything (~2 levels).", level: "14 (catch-up)", danger: "Sprint" },
    { act: "Act 2", title: "Mawdun Mine", body: "Push up to the boss, kill with the same combo, free the Faradun prisoner.", level: "15", danger: "Cautious" },
    { act: "Act 2", title: "Vendors", body: "Back at the caravan, check vendors for a minion-skill scepter + helm." },
    { act: "Act 2", title: "Traitors Passage", body: "Likely a level-6 skill gem here — upgrade Ember Fusillade. Save ALL other skill gems from now on (need 2 more by Trial of Sekhemas).", level: "16", danger: "Sprint" },
    { act: "Act 2", title: "Balbala", body: "Find Balbala, fight with the same combo, get the Trial key.", level: "16", danger: "Sprint" },
    { act: "Act 2", title: "Halani Gates → Jamanra", body: "Clear the Halani Gates, then fight Jamanra with the same boss combo.", level: "16", danger: "Cautious" },
    { act: "Act 2", title: "Gamble scepter", body: "Back at the caravan: if no minion scepter/helm yet, gamble for a scepter." },
    { act: "Act 2", title: "Trial of Sekhemas → Varashta", body: "Complete the Trial. Choose Varashta → right side of the tree → Kari's Deception.", level: "18", danger: "Sprint" },
    { act: "Act 2", title: "BUILD SWAP: strip gems", body: "Take out all skill + support gems EXCEPT Magnified Area and Pounce. Sell the rest. Put Magnified Area on Kari's Deception." },
    { act: "Act 2", title: "Bidding → Kari's Deception", body: "Use a level-2 support gem to put Bidding I into Kari's Deception." },
    { act: "Act 2", title: "Skeletal Snipers + Thunderstorm", body: "Use the two saved skill gems to make Skeletal Snipers and Thunderstorm." },
    { act: "Act 2", title: "Concentrated Area → Kari's Command", body: "Use a support gem for Concentrated Area on Kari's Command. Swap to Magnified Area for clear, Concentrated for bosses." },
    { act: "Act 2", title: "Prolonged Duration → Pounce", body: "Use a support gem for Prolonged Duration on Pounce." },
    { act: "Act 2", title: "Equip skills", body: "Equip Kari's Brutality, Kari's Deception, Pounce, Thunderstorm on the bar. Keep max Skeletal Snipers up. Equip scepter + helm.", loadout: [{skill: "Kari's Deception", supports: ["Magnified Area", "Bidding I"]}, {skill: "Kari's Brutality"}, {skill: "Pounce", supports: ["Prolonged Duration"]}, {skill: "Thunderstorm"}, {skill: "Skeletal Snipers"}] },
    { act: "Act 2", title: "Rebuild passive tree", body: "Refund + reconstruct the tree per the guide. FIRST FOUR attribute nodes = Strength (lets Thunderstorm keep drenching into late game)." },
    { act: "Act 2", title: "Boss rotation (memorize)", body: "Pounce → Thunderstorm → Kari's Brutality ×2 → Kari's Deception ×3 → Kari's Brutality ×2 → Kari's Deception ×2 → repeat.", meta: "Every boss" },
    { act: "Act 2", title: "Mastodon Badlands", body: "Find the effigy, get the second level-2 support gem → Mark for Death on Pounce.", level: "22 (catch-up)", danger: "Sprint", loadout: [{skill: "Kari's Deception", supports: ["Magnified Area", "Bidding I"]}, {skill: "Kari's Brutality"}, {skill: "Pounce", supports: ["Mark for Death", "Prolonged Duration"]}, {skill: "Thunderstorm"}, {skill: "Skeletal Snipers"}] },
    { act: "Act 2", title: "Bone Pits", body: "Swap Magnified → Concentrated, kill the boss with the rotation.", level: "23", danger: "Sprint" },
    { act: "Act 2", title: "Living Lightning", body: "Back to town, third level-2 support gem → Living Lightning on Thunderstorm. You're fully online now.", loadout: [{skill: "Kari's Deception", supports: ["Magnified Area", "Bidding I"]}, {skill: "Kari's Brutality"}, {skill: "Pounce", supports: ["Mark for Death", "Prolonged Duration"]}, {skill: "Thunderstorm", supports: ["Living Lightning"]}, {skill: "Skeletal Snipers"}] },
    { act: "Act 2", title: "Keth", body: "Swap back to Magnified. Kill the serpent boss (Concentrated for the fight).", level: "21", danger: "Sprint" },
    { act: "Act 2", title: "Lost City → Heart of Keth", body: "Lost City → Buried Shrines → Heart of Keth. Kill the boss (Concentrated).", level: "22", danger: "Cautious" },
    { act: "Act 2", title: "Level 22: Arsonist", body: "At level 22, get Skeletal Arsonist + Last Gasp support.", level: "22", loadout: [{skill: "Kari's Deception", supports: ["Magnified Area", "Bidding I"]}, {skill: "Kari's Brutality"}, {skill: "Pounce", supports: ["Mark for Death", "Prolonged Duration"]}, {skill: "Thunderstorm", supports: ["Living Lightning"]}, {skill: "Skeletal Snipers", supports: ["Last Gasp"]}, {skill: "Skeletal Arsonist", supports: ["Last Gasp"]}] },
    { act: "Act 2", title: "Valley of the Titans", body: "Find the 3 ancient seals, unlock the Grotto, kill the boss.", level: "22", danger: "Sprint" },
    { act: "Act 2", title: "Blow the horn", body: "Return to town, blow the horn at the Halani Gates to unlock the Dreadnought." },
    { act: "Act 2", title: "Fallen Rowa", body: "Find the Fallen Rowa for skill points." },
    { act: "Act 2", title: "Path of Morning", body: "Path of Morning → Spires of Deshar → bonus lightning-resist shrine → kill the boss.", level: "25", danger: "Sprint" },
    { act: "Act 2", title: "Gamble +2 scepter", body: "At level 25, gamble for a +2 minion-skill scepter.", level: "25" },
    { act: "Act 2", title: "Dreadnought → Jamanra", body: "Hit at least level 28 before Jamanra. Kill him with the standard rotation.", level: "28", danger: "Dangerous" },

    { act: "Act 3", title: "Sandswept Marsh", body: "Fight through to the Ziggurat Encampment, talk to everyone.", level: "29", danger: "Sprint" },
    { act: "Act 3", title: "Jungle Ruins", body: "Layout changed this patch — follow quest markers. Usual: Jungle Ruins → (monkey) → Venom Crypt → Infested Barrens → Chimeral Wetlands → Jiquani Sanctum.", level: "30", danger: "Sprint" },
    { act: "Act 3", title: "Non-campaign objectives", body: "Complete the 3 non-quest things: monkey, AOC witch, Venom Crypt." },
    { act: "Act 3", title: "Venom Crypt reward", body: "Choose stun-threshold as the Venom Crypt reward." },
    { act: "Act 3", title: "Jiquani Sanctum", body: "Fight Lizard Boy, get fire resist.", level: "33", danger: "Cautious" },
    { act: "Act 3", title: "Jiquani's Machinarium", body: "Put two big rocks in the round holes, fight the boss.", level: "32", danger: "Cautious" },
    { act: "Act 3", title: "Matlan Waterways", body: "Clear the (redesigned) Matlan Waterways.", level: "34 (catch-up)", danger: "Cautious" },
    { act: "Act 3", title: "Drowned City → Molten Vaults", body: "Drowned City → find Molten Vaults → kill the boss.", level: "35 (catch-up)", danger: "Cautious" },
    { act: "Act 3", title: "Apex of Filth", body: "Back to Drowned City → Apex of Filth → kill the boss.", level: "36", danger: "Cautious" },
    { act: "Act 3", title: "Temple of Kopec", body: "Fight to and kill the Temple of Kopec boss.", level: "37", danger: "Cautious" },
    { act: "Act 3", title: "Utzaal / Aggorat", body: "Kill the big guys for the Sacrificial Heart. Pay attention for the drop.", level: "38 (catch-up)", danger: "Death Wish" },
    { act: "Act 3", title: "Napoatsi", body: "Defeat Napoatsi.", level: "38 (catch-up)", danger: "Death Wish" },
    { act: "Act 3", title: "Sacrificial Heart", body: "In the Aggorat, find the Sacrificial Heart for your points.", level: "39", danger: "Dangerous" },
    { act: "Act 3", title: "Black Temple → Doryani", body: "Fight through the Black Temple, defeat Doryani.", level: "40", danger: "Dangerous" },

    { act: "Act 4", title: "Charter → sail", body: "Talk to Alva for the charter. Boat → sail to Keday." },
    { act: "Act 4", title: "Journey's End", body: "Fight through Keday into Journey's End. Defeat Captain Tentacles, TP to town.", level: "48", danger: "Cautious" },
    { act: "Act 4", title: "Rune spike + helm gamble", body: "Get the rune spike. At level 41, gamble for a +2 minion-skill helm.", level: "41" },
    { act: "Act 4", title: "Delarium", body: "Back to Journey's End: put spikes in the stones, defeat the Delarium encounter.", level: "48", danger: "Cautious" },
    { act: "Act 4", title: "Isle of Kin", body: "Sail to the Isle of Kin. Find the mini-boss (blankaroon) and the caged beast → level-4 support gem.", level: "41", danger: "Cautious" },
    { act: "Act 4", title: "Bidding II", body: "Use that support gem to upgrade Bidding I → Bidding II." },
    { act: "Act 4", title: "Volcanic Warren", body: "Kill the two mini-bosses for the Topaz ring (resistances), then the main boss.", level: "41", danger: "Sprint" },
    { act: "Act 4", title: "Whakapanu → Singing Caverns", body: "Sail to Whakapanu, fight into the Singing Caverns, defeat the killer mermaid, grab the pearl.", level: "45", danger: "Cautious" },
    { act: "Act 4", title: "Pearl amulet", body: "Turn the pearl in to Rag for a pearl amulet." },
    { act: "Act 4", title: "Delirium on amulet", body: "Allocate delirium on the amulet: pink → green → yellow (paranoia, not greed). Grants Long-Distance Relationship." },
    { act: "Act 4", title: "Abandoned Prison", body: "Kill until the chapel key drops. Find the chapel → choose mana regeneration.", level: "46", danger: "Cautious" },
    { act: "Act 4", title: "Solitary Confinement", body: "Fight to and defeat the boss.", level: "47", danger: "Cautious" },
    { act: "Act 4", title: "Shrike Island", body: "Fight through and defeat Big Bird. Talk to Malachi.", level: "44 (catch-up)", danger: "Death Wish" },
    { act: "Act 4", title: "Eye of Hinora", body: "First 3 trials. After the 3rd, grab +5% max mana.", level: "42", danger: "Sprint" },
    { act: "Act 4", title: "Halls of the Dead", body: "Defeat all 3 trials again — choose resistances for all three.", level: "43", danger: "Cautious" },
    { act: "Act 4", title: "Yama", body: "Defeat Yama, claim 2 more skill points.", level: "43", danger: "Cautious" },
    { act: "Act 4", title: "Arstus", body: "Speak to the Hooded One → travel to Arstus.", level: "48", danger: "Dangerous" },
    { act: "Act 4", title: "Sea-city bluffs", body: "At the bluffs checkpoint: toward the ocean = 3 exalted orbs; inland = 3 regals. Kill the mini-boss.", level: "48", danger: "Dangerous" },
    { act: "Act 4", title: "Excavation", body: "Fight through to the boss, defeat him, brace for the flashbang.", level: "49 (catch-up)", danger: "Cautious" },
    { act: "Act 4", title: "Ngakanu", body: "Fight through the harder tribe, defeat the last boss.", level: "50", danger: "Dangerous" },

    { act: "Interlude", title: "Interludes", body: "Interludes are easy now. Watch the map for 4 quests that give extra passive points — vital for min-maxing." },
  ],
};
